version: 2.0
jobs:
  build:
    docker:
      - image: fedora
    working_directory: ~/repo
    steps:
      - checkout
      - run: dnf install -y fedora-packager
      - run: ./build.sh      
      - store_artifacts:
          path: x86_64
