version: 2.0
jobs:
  build:
    docker:
      - image: fedora
    working_directory: ~/repo
    steps:
      - checkout
      - run: dnf install -y fedora-packager
      - run: ./build.sh      
      - run: ls -lah x86_64/
      - run: mv x86_64/* $CIRCLE_ARTIFACTS/
      - run: ls -lah $CIRCLE_ARTIFACTS/
