version: 2.0
general:
  artifacts:
    - "x86_64"    
jobs:
  build:
    docker:
      - image: fedora
    working_directory: ~/repo
    steps:
      - checkout
      - run: dnf install -y fedora-packager
      - run: ./build.sh      
